### ISSUE TITLE
ONNX Demo example not working with Jetson Xavier NX

### ISSUE THREAD

**Issue by isra60** [Kazuhito00/YuNet-ONNX-TFLite-Sample#1]
Hi. First things first, thank you for you repo !!
 I'm just testing the ONNX demo code and I encountered the following error.

> python3 sample_onnx.py --width 640 --height 480
>  Traceback (most recent call last):
>   File "sample_onnx.py", line 179, in <module>
>     main()
>   File "sample_onnx.py", line 101, in main
>     bboxes, landmarks, scores = yunet.inference(frame)
>   File "/workspace/YuNet-ONNX-TFLite-Sample/yunet/yunet_onnx.py", line 59, in inference
>     bboxes, landmarks, scores = self._postprocess(result)
>   File "/workspace/YuNet-ONNX-TFLite-Sample/yunet/yunet_onnx.py", line 143, in _postprocess
>     dets = np.squeeze(dets, axis=1)
>   File "<__array_function__ internals>", line 6, in squeeze
>   File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 1495, in squeeze
>     return squeeze(axis=axis)
> ValueError: cannot select an axis to squeeze out which has size not equal to one

I'm using the default tensorflow docker from nvdia (other onnx models works such as yours of movenet multipose) with these packages installed

onnxruntime-gpu         1.8.0
opencv-python           4.5.4.58
tensorflow              2.5.0+nv

**Comment by Kazuhito00** [comment]
I don't have Jetson Xavier NX.
Can you tell us the following two points?
・ Numpy version
・The value of dets before calling np.squeeze()

**Comment by isra60** [comment]
* Numpy version:
   numpy                   1.19.5
* dets value:
  print(dets)
  [[127.48315359  68.4570952   37.57986974  43.9153489  141.534338
   88.51420641 158.69068146  86.14562988 151.0201931   96.21218204
  146.34729385 105.41690826 159.93618011 103.54684353   0.94473016]]

**Comment by Kazuhito00** [comment]
Thank you.
It doesn't seem to be the shape I'm expecting. I will investigate.

By the way, does it work if you comment out line 143?
```
        if len(keepIdx) > 0:
            dets = dets[keepIdx]
            # dets = np.squeeze(dets, axis=1)
            for det in dets[:self.keep_topk]:
                scores.append(det[-1])
                bboxes.append(det[0:4].astype(np.int32))
                landmarks.append(det[4:14].astype(np.int32).reshape((5, 2)))
```

**Comment by ibaiGorordo** [comment]
I had the same issue in Windows, and also with the tflite example. Commenting the np.squeeze line solved the problem.

**Comment by Kazuhito00** [comment]
The root cause is unknown, but I changed it to np.squeeze () according to the shape.
