### ISSUE TITLE
What should I do for using uint8 quantized model?

### ISSUE THREAD

**Issue by jylee256** [Kazuhito00/YuNet-ONNX-TFLite-Sample#2]
Dear @Kazuhito00, First of all, thanks for your yunet model.

There are many quantized yunet model in your model directory, and 'model_full_integer_quant.tflite' is also one of those.
It seems that your codes (sample_tflite.py , yunet_tflite.py) are for only model_float16_quant.tflite or model_float32.tflite, and it works well.
But I wanted to use the integer quantized model (model_full_integer_quant.tflite), so I modified your sample codes like below, and run it.

############################################################
**<yunet/yunet_tflite.py>**
![image](https://github.com/Kazuhito00/YuNet-ONNX-TFLite-Sample/assets/29939537/59d35eae-157b-4584-bacd-760ff8f79947)

**#########################################################
$ python3 sample_tflite.py --model=model/model_full_integer_quant.tflite**

However, it didn't work. 
When I print all of the confidence output raw data (print('conf[', 2*i+1, '] ', sc1)), there are no 'high' score close to the 255 value.
I think the confidence score should be 0~255, and the best score should be close to 255, but any output is not that.
(The highest score in this model was just 12...)

Have you ever validated this int8/uint8 quantized model? If so, could you tell me what I have to modify the sample codes?

**Comment by Kazuhito00** [comment]
Sorry, I have never verified the int8/uint8 quantization model.
